#!/bin/sh
set -eu

SCHEMA_NAME="${DB_SCHEMA:-attendance}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE SCHEMA IF NOT EXISTS "$SCHEMA_NAME";
GRANT ALL ON SCHEMA "$SCHEMA_NAME" TO "$POSTGRES_USER";
EOSQL
